//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ContactId { get; set; }
        public string Address { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string FirstMidName { get; set; }
        public Nullable<long> ImageID { get; set; }
        public string LastName { get; set; }
        public string OwnerID { get; set; }
        public string WhereIdentityCard { get; set; }
        public int Status { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> DateIdentityCard { get; set; }
        public string Landline { get; set; }
        public int Sex { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Image Image { get; set; }
    }
}
